include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/**/*.mapper.dart
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true
    always_use_package_imports: false
    