include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true
    always_use_package_imports: false
    