global_options:
  dart_mappable_builder:
    options:
      # the case style for the map keys, defaults to 'none'
      caseStyle: none # or 'camelCase', 'pascalCase', 'snakeCase', 'paramCase', 'lowerCase', or 'upperCase'.
      # the case style for stringified enum values, defaults to 'none'
      enumCaseStyle: none # or 'camelCase', 'pascalCase', 'snakeCase', 'paramCase', 'lowerCase', or 'upperCase'.
      # if true removes all map keys with null values
      ignoreNull: false # or true
      # used as property name for type discriminators
      discriminatorKey: type
      # used to specify which methods to generate (all by default)
      generateMethods: [copy, stringify, equals] # [decode, encode, copy, stringify, equals]