name: owolf
description: A Pomodoro X Flowtime app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  common:
    path: packages/common
  cupertino_icons: ^1.0.2
  dart_mappable: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.20.1
  flutter_ringtone_player: ^3.2.0
  intl: ^0.18.1
  path_provider: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  dart_mappable_builder: ^3.2.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
