name: owolf
description: A Pomodoro X Flowtime app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_mappable: ^3.2.0
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.20.1
  flutter_ringtone_player: ^3.2.0
  go_router: ^11.1.2
  intl: ^0.18.1
  path_provider: ^2.0.15
  settings_repository:
    path: packages/settings_repository
  utility:
    path: packages/utility

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.3.3
  dart_mappable_builder: ^3.2.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
