name: owolf
description: A Pomodoro X Flowtime app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_mappable: ^4.6.0
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_ringtone_player: ^4.0.0
  go_router: ^16.1.0
  intl: ^0.20.2
  path_provider: ^2.0.15
  settings_repository:
    path: packages/settings_repository
  utility:
    path: packages/utility

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  dart_mappable_builder: ^4.6.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
